Port CottonRPG to 1.16
CottonMC/CottonRPG pull request #4
Opened 2020-10-25 15:38 UTC by Pyrofab

This PR:
1. ports CottonRPG to 1.16
2. replaces mixins with usage of Cardinal Components API and Fabric events
3. refactors a lot of internals to minimize duplicated code
4. makes usage of Prerequisites a bit more fluent through factory methods
5. replaces identifiers with the actual registry objects in most places
6. cleans up and stuff

2020-10-25 21:25 UTC, Boundarybreaker requested changes
Looking really, really good! I just wanna note a couple of things:

2020-10-25 21:25 UTC, LemmaEOF commented on .editorconfig
> +root = true
shouldn't this be gitignore'd?

2020-10-25 21:25 UTC, LemmaEOF commented on src/main/java/io/github/cottonmc/cottonrpg/CottonRPG.java
> +	public static Identifier id(String remnant_states) {
`remnant_states`?

2020-10-25 21:25 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/CottonRPGConfig.java
>  //TODO: how do we wanna do this? Nest in Jankson?
this can be fixed now that Jankson-Fabric is a thing

2020-10-25 21:25 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/client/RpgHud.java
> +				//      x                    y    w         h    u  v
looks weird outside of an IDE but that doesn't really matter

2020-10-25 21:25 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/commands/CottonRPGCommands.java
> +		CommandRegistrationCallback.EVENT.register((CommandDispatcher<ServerCommandSource> cmd, boolean dedicated) -> cmd.register(CommandManager.literal("cottonrpg")
...not actually sure why falk explicitly typed these

2020-10-25 21:25 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/data/BaseRpgDataContainer.java
> +	public boolean has(T skill) {
if this is genericed, it probably shouldn't be called `skill` for the arg.

2020-10-25 21:25 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/data/ProxyRpgDataContainer.java
> +public abstract class ProxyRpgDataContainer<T extends RpgDataType, E extends RpgDataEntry<T>> extends BaseRpgDataContainer<T, E> {
is it necessary to have both `ProxyCharacterData` and `ProxyRpgDataContainer`? Same goes for `CharacterData and `RpgDataContainer`, really.

2020-10-25 21:25 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/data/clazz/CharacterClass.java
>  package io.github.cottonmc.cottonrpg.data.clazz;
uuuuuggggghhhhh I hate how Java makes me do this, could this package be `cclass` instead maybe

2020-10-25 21:25 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/data/clazz/CharacterClassEntry.java
> +	public void writeToPacket(PacketByteBuf buf) {
VarInts in read/write maybe?

2020-10-25 22:04 UTC, Pyrofab commented on src/main/java/io/github/cottonmc/cottonrpg/CottonRPG.java
> +	public static Identifier id(String remnant_states) {
Huh. That's the result of copy-pasting + idea automatic refactors.

2020-10-25 22:18 UTC, Pyrofab commented on .editorconfig
> +root = true
probably not, it's useful to configure IDEs automatically (https://editorconfig.org/)

2020-10-25 22:22 UTC, Boundarybreaker commented on .editorconfig
> +root = true
got it, I thought it was an IDE-specific file

2020-10-25 22:23 UTC, Boundarybreaker commented on src/main/java/io/github/cottonmc/cottonrpg/CottonRPGConfig.java
>  //TODO: how do we wanna do this? Nest in Jankson?
I'll do this myself once it's merged

2020-10-27 00:29 UTC, Boundarybreaker approved these changes

2020-10-27 00:30 UTC, Boundarybreaker commented
Looking good to me! I'll merge and put it up to the maven. If you find any other issues, lemme know!

2020-10-27 00:30 UTC, merged